module.exports = {
  source: ['design-tokens/tokens-transformed.json'],
  fileHeader: {
    autoGeneratedFileHeader: () => {
      return [`!!Do not edit directly, this file was auto-generated!!`];
    },
  },
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'src/css/base/',
      // prefix: 'figma',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: {
            fileHeader: 'autoGeneratedFileHeader',
          },
        },
      ],
    },
  },
};
